server:
  port: 8002
  servlet:
    context-path: /content-service
spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    top.mqxu.share.user.mapper: debug
#server:
#  port: 8000
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: route-user
#          uri: http://127.0.0.1:8001
#          predicates:
#            - Path=/user-service/**
#        - id: route-content
#          uri: http://127.0.0.1:8002
#          predicates:
#            - Path=/content-service/**
#  servlet:
#    context-path: /user-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/content-center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#logging:
#  level:
#    top.mqxu.share.user.mapper: debug