server:
  port: 8002
  servlet:
    context-path: /content-service
spring:
  application:
    name: content-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    top.mqxu.share.user.mapper: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
rocketmq:
  #  name-server: 127.0.0.1:9876
  name-server: 118.31.22.25:9876
  producer:
    group: test-group
    send-message-timeout: 600000

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.share.content.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn