
PUT http://localhost:8000/user-service/user/update-bonus
###
POST http://localhost:8000/user-service/user/register
Content-Type: application/json

{"phone": "13951908866",
  "password": "123123"}

###
POST http://localhost:8000/user-service/user/login
Content-Type: application/json

{
  "phone": "13951905171",
  "password": "123123"
}

> {%
    client.global.set("token",response.body.data.token);
  %}


###
GET http://localhost:8000/user-service/user/count
Accept: application/json
token: {{token}}

###
GET http://localhost:8000/user-service/hello
Accept: application/json

###
GET http://localhost:8081/user-service/hello
Accept: application/json

###
GET http://localhost:8000/user-service/hello
Accept: application/json





