server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: dev
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: route-user
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/user-service/**
        - id: route-service
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
            allow-credentials: 'true'
            maxAge: '3600'

