server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: route-user
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/user-service/**
        - id: route-service/**
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
            allow-credentials: 'true'
            maxAge: '3600'

